version: "3.6"

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
  
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Password12!"
    ports:
      - 1433:1433
  
  # cosmosdb: 
  #   image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator"
  #   # memory_limit: 2gb
  #   cpus: 2
  #   environment:
  #     - "AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10" 
  #     - "AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true" 
  #     - "AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=192.168.86.212"
  #   ports:
  #   - "8081:8081" 
  #   - "10251:10251" 
  #   - "10252:10252" 
  #   - "10253:10253" 
  #   - "10254:10254"
  
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    ports:
      - "${SEQ_PORT}:80"
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
  
  api:
    image: forkjoint/api
    build:
      context: ./src
      dockerfile: Dockerfile.api
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Passw0rd"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
      - "ASPNETCORE_URLS=https://+:443;http://+:80"
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_TYPE=remote"
      - "JAEGER_SAMPLING_ENDPOINT=http://jaeger:5778/sampling"
    volumes:
      - ~/.aspnet/https:/https/:ro
#      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

