version: "3.8"

x-loki-logging:
  &loki-logging
  driver: loki
  options:
    loki-url: http://localhost:3100/loki/api/v1/push
    mode: non-blocking
    loki-retries: 2
    keep-file: "true"
    max-size: "10m"
    max-file: 5

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

  mssql:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=Password12!"
    ports:
      - 1433:1433

  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:80"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  tempo:
    image: grafana/tempo:1.0.1
    command:
      - -config.file=/etc/tempo-config.yaml
    ports:
      - "4317:4317" # gRPC
    depends_on:
      - loki
    logging: *loki-logging
    configs:
      - source: tempo-config
        target: /etc/tempo-config.yaml

  loki:
    image: grafana/loki:2.3.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    logging: *loki-logging

  prometheus:
    image: prom/prometheus:v2.28.1
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    depends_on:
      - loki
    logging: *loki-logging
    configs:
      - source: prometheus-config
        target: /etc/prometheus.yaml

  grafana-agent:
    image: grafana/agent:latest
    command: "-config.file=/etc/agent-config.yaml"
    ports:
      - "14317:4317" # gRPC
      - "14318:4318" # http
    configs:
      - source: grafana-agent-config
        target: /etc/agent-config.yaml

  grafana:
    image: grafana/grafana:7.5.10
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      # - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN}
      # - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      # - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - "3001:3000"
    depends_on:
      - loki
    logging: *loki-logging
    configs:
      - source: grafana-dashboard-config
        target: /etc/grafana/provisioning/dashboards/dashboards.yaml
      - source: grafana-datasource-config
        target: /etc/grafana/provisioning/datasources/datasource.yml

configs:
  grafana-agent-config:
    file: ./docker/grafana-agent/agent-config.yaml
  grafana-dashboard-config:
    file: ./docker/grafana/provisioning/dashboards/dashboards.yaml
  grafana-datasource-config:
    file: ./docker/grafana/provisioning/datasources/datasource.yml
  tempo-config:
    file: ./docker/tempo/tempo.yaml
  prometheus-config:
    file: ./docker/prometheus/prometheus.yaml
