# @name=order

POST https://localhost:5001/Order
Content-Type: application/json

{
  "orderId": "{{$random.uuid}}",
  "burgers": [
    {
      "burgerId": "{{$random.uuid}}",
      "weight": 2,
      "lettuce": false,
      "cheese": true,
      "pickle": true,
      "onion": true,
      "ketchup": true,
      "mustard": true,
      "barbecueSauce": true,
      "onionRing": true
    }
  ],
  "fries": [
    {
      "fryId": "{{$random.uuid}}",
      "size": 1
    }
  ],
  "shakes": [
    {
      "shakeId": "{{$random.uuid}}",
      "flavor": "Strawberry",
      "size": 1
    }
  ],
  "fryShakes": [
    {
      "fryShakeId": "{{$random.uuid}}",
      "flavor": "Banna",
      "size": 1
    }
  ]
}
