global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3100"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "factory"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["factory:8080"]

  - job_name: "recipes"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["recipes:8080"]

  - job_name: "jobs"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["jobs:8080"]

  - job_name: "activities"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["activities:8080"]
